Cf 400/dark mode improvements
csesoc/Circles pull request #1003
Opened 2023-03-19 03:13 UTC by Dasyure

@leonardo-fan this was what I was talking about in my standup from Wednesday. This draft PR contains three commits but the one in question is the last one that deals with adding dark mode to the settingsMenu's select dropdown, inside SettingsMenu.tsx. I added pictures on the jira ticket of the end product if you're interested. 

What I tried to do:
- Initially I made a new style.ts file where I used styled components to import and edit an antd Input element, then export it back to SettingsMenu.tsx. However it didn't work.
- I tried to use the given dropdownStyle property, as per the antd documentation. However it only partially worked.
What I ended up doing:
- I edited GlobalStyles in src/config/theme.ts and used the !important property to override the antd styles. 
Concern:
- is there a cleaner way of overriding the antd styles? I spent a while trying to figure it out but failed to.

2023-03-21 14:12 UTC, Dasyure commented
https://ant.design/docs/react/customize-theme
One potential solution would be to upgrade to v5 for antd and play around with this. The downside of doing this is:
1. It doesn't work perfectly because antd hasn't been customisable with past versions
2. Having to rewrite a lot of code that uses antd due to migrating to v5

2023-04-04 09:06 UTC, leonardo-fan requested changes
Really great job with all the changes! Looks good, just some small comments regarding unused class names. 

Also had a bit of a test and there are some remaining dark mode things that I saw (refer to videos/images below). Since there are a few dependencies on this pr right now - definitely don't feel pressured to get these improvements done now. Let me know if you still want to do them, otherwise I'll put the further fixes in the backlog

<img width="323" alt="Screenshot 2023-04-04 at 7 03 19 pm" src="https://user-images.githubusercontent.com/90736577/229743511-29ca7b18-9fd4-40f3-b23a-8992714ed0ad.png">
<img width="343" alt="Screenshot 2023-04-04 at 7 03 26 pm" src="https://user-images.githubusercontent.com/90736577/229743521-34e9f91d-f182-40d6-a5d3-2f8168d73ff8.png">

https://user-images.githubusercontent.com/90736577/229743529-9c47dd10-0f77-43f8-8185-594919945e72.mov


https://user-images.githubusercontent.com/90736577/229743542-cc73aa24-54f4-4b48-a6c3-e9e7f640cd95.mov


https://user-images.githubusercontent.com/90736577/229743549-3ae3a9ef-0bbc-4fcd-95e7-71a6afd51e06.mov


https://user-images.githubusercontent.com/90736577/229743561-88e82f18-e93d-44c6-aa85-8d7b24bcd864.mov


https://user-images.githubusercontent.com/90736577/229743571-713a3329-0198-42d0-80aa-c1a3df0f4181.mov

2023-04-04 09:06 UTC, leonardo-fan commented on frontend/src/components/CourseDescriptionPanel/CourseInfoDrawers.tsx
> +    <div className="course-info-drawers">
doesn't seem like this is used/defined - should remove

2023-04-04 09:06 UTC, leonardo-fan commented on frontend/src/components/SidebarDrawer/SidebarDrawer.tsx
> +    <S.Wrapper open={open} className="sidebar-drawer">
className not defined

2023-04-04 09:06 UTC, leonardo-fan commented on frontend/src/pages/TermPlanner/SettingsMenu/SettingsMenu.tsx
> +      <CS.PopupEntry className="settings-start-year-popup">
no className definition

2023-04-05 03:42 UTC, Dasyure commented
@leonardo-fan Thanks for pointing those out, I'm happy to finish off the dark mode features I forgot to cover. 

The only issue is there are a 3 other PRs which are dependent on this. Should I just wait for all 4 PRs to be merged in and then fix all the issues afterward in one go?

2023-04-11 10:20 UTC, leonardo-fan commented
> Really great job with all the changes! Looks good, just some small comments regarding unused class names.
> 
> Also had a bit of a test and there are some remaining dark mode things that I saw (refer to videos/images below). Since there are a few dependencies on this pr right now - definitely don't feel pressured to get these improvements done now. Let me know if you still want to do them, otherwise I'll put the further fixes in the backlog

refer to https://csesoc.atlassian.net/jira/software/projects/CF/boards/12/backlog?selectedIssue=CF-426 for further dark mode fixes after this PR is merged in

2023-04-11 13:40 UTC, leonardo-fan approved these changes

2023-04-11 13:45 UTC, merged