Add option to ignore course in progression checks
csesoc/Circles pull request #1059
Opened 2023-06-19 10:32 UTC by lhvy

2023-07-13 09:34 UTC, leonardo-fan requested changes, later dismissed
Big props Lucas for taking the initiative for this new improvement/feature. Most things look good to me, I've noticed some fixes that would be good though:
- ignoring from progression doesn't get updated in the dashboard cards (refer below) -> add similar logic to the `storeUOC[group].curr` key
<img width="1335" alt="image" src="https://github.com/csesoc/circles/assets/90736577/7f29b56f-8464-48f8-9eb0-230699db5e57">
- can you please upload a new gif to the help menu so it's consistent with what we have now
<img width="971" alt="image" src="https://github.com/csesoc/circles/assets/90736577/5e279e7b-4593-42f4-b57e-fc2124955953">
- see comment about generic new progression checker section that you could feed elements/text into

2023-07-13 09:34 UTC, leonardo-fan commented on frontend/src/pages/ProgressionChecker/IgnoredCoursesSection/IgnoredCoursesSection.tsx
Hahaha I see what you were talking about before basically repeating `FreeElectiveSection.tsx`. If you want, it'd be useful to have a generic template that you could pass title/subheading1/subheading2 text into if we want to add more sections in the future/reduce the repetition.

2023-07-13 09:34 UTC, leonardo-fan commented on frontend/src/pages/ProgressionChecker/IgnoredCoursesSection/IgnoredCoursesSection.tsx
> +        You have {uoc} UOC worth of additional courses ignored from your progression
no need for "additional"

2023-08-13 04:28 UTC, lhvy commented on frontend/src/pages/ProgressionChecker/IgnoredCoursesSection/IgnoredCoursesSection.tsx
> +        You have {uoc} UOC worth of additional courses ignored from your progression
Fixed

2023-08-13 04:28 UTC, lhvy commented on frontend/src/pages/ProgressionChecker/IgnoredCoursesSection/IgnoredCoursesSection.tsx
Done 👍

2023-08-15 12:31 UTC, leonardo-fan approved these changes
perfecto lgtm :) thanks Lucas!

2023-08-15 14:09 UTC, imagine-hussain approved these changes
Looks good!!!!!!

2023-08-15 14:11 UTC, merged