Christian/feat/add login page
csesoc/Circles pull request #1073
Opened 2023-09-04 10:49 UTC by ui-Auxilary

Fixed up some bugs in the Landing page ie. gap at the footer, and animation not repeating for Circle logo

- Added login page

2023-09-05 14:44 UTC, imagine-hussain reviewed
This is looking great!

Just some minor points:

- at medium laptop width (around the 1200-1024 px mark), the horizontal margins on the container are probably a little big and make the login look smaller than we want.


<img width="1082" alt="image" src="https://github.com/csesoc/circles/assets/93496985/edf18640-974a-41ff-b481-eb421153bfcd">

- Since removing google, we should now be replacing that with a "continue as guest" option

2023-09-05 14:50 UTC, imagine-hussain commented
Forgot to mention, this should also have a dark-mode implementation, though that doesn't necessarily need to be done this PR since this isn't directly going to production, that would be the next thing to look at.

2023-09-14 09:47 UTC, leonardo-fan requested changes
Looks awesome! same comment as Hussain on the L & R margins. One grammar thing in comments. Also thoughts on keeping the login container centered vertically as well?

2023-09-14 09:47 UTC, leonardo-fan commented on frontend/src/pages/Auth/Container/Container.tsx
> +            <h2>Login to circles</h2>
"Login to Circles"

2023-10-21 05:04 UTC, ollibowers commented on frontend/src/pages/Auth/Auth.tsx
>    const JsonObject = ({ obj }: Props) => {
If no progress was made towards google login, should we just remove this?

2023-10-21 05:04 UTC, ollibowers commented on frontend/src/pages/Auth/Auth.tsx
>    const handleCallbackResponse = (response: any) => {
Google?

2023-10-21 05:05 UTC, ollibowers commented on frontend/src/pages/Auth/Auth.tsx
>    useEffect(() => {
Agan google

2023-10-21 05:07 UTC, ollibowers commented on frontend/src/pages/Auth/Auth.tsx
> +  const [dummyToken, setDummyToken] = useState('');
I don't think this state is used anymore

2023-10-21 05:08 UTC, ollibowers commented on package-lock.json
i dont know if this should be here

2023-10-21 05:10 UTC, ollibowers requested changes
oops i did the changes as comments

2023-10-26 13:43 UTC, imagine-hussain commented on frontend/src/pages/Auth/Auth.tsx
>    const handleCallbackResponse = (response: any) => {
Googlie die

2023-11-07 10:15 UTC, imagine-hussain approved these changes
LGTM!!!

2023-11-07 10:15 UTC, imagine-hussain commented
I wonder if I have to manually merge this because of failing pipelines of if this should work

2024-02-04 21:34 UTC, Peedee2002 commented
This has been merged

2024-02-04 21:34 UTC, closed without merging