chore(fe): Fix deprecations and breaking changes in deps
csesoc/Circles pull request #1154
Opened 2024-06-21 05:57 UTC by lhvy

2024-07-02 16:50 UTC, ollibowers requested changes
other then that one missed spot, looks good to me

2024-07-02 16:50 UTC, ollibowers commented on frontend/src/pages/TermPlanner/TermBox/styles.ts
> +const TermCheckboxWrapper = styled.div<{ $checked: boolean }>`
`frontend/src/pages/TermPlanner/TermBox/TermBox.tsx:107` is not converted to transient 😡

you forgor 💀

2024-07-02 16:52 UTC, ollibowers commented on frontend/src/pages/TermPlanner/TermBox/styles.ts
> +const TermCheckboxWrapper = styled.div<{ $checked: boolean }>`
dont forget to run `npm run types`, silly

2024-07-03 03:37 UTC, lhvy commented on frontend/src/pages/TermPlanner/TermBox/styles.ts
> +const TermCheckboxWrapper = styled.div<{ $checked: boolean }>`
Oops. Fixed thanks.

2024-07-03 08:21 UTC, ollibowers approved these changes
lgtm

2024-07-03 08:25 UTC, merged