Circles 241 peter/integrate program type
csesoc/Circles pull request #166
Opened 2022-01-09 12:05 UTC by Peedee2002

added code to match some of the common cases and to get the logic parsed, but will need to rerun some of the scripts to clean final data and remove some of the manual changes likely.

2022-01-11 09:32 UTC, JamesyJi requested changes

2022-01-14 10:28 UTC, Peedee2002 commented on backend/data/processors/conditions_preprocessing.py
> +def convert_program_type(processed):
i think that the way I have it for now is flexible for something like that. the map_word_to_program_type specifies that it must specify "program" or "degree" which is not ambiguous like "courses." I dont know too much about zbus - is that canberra? Are we supporting canberra concurrently? If we are - that would have much larger reprecussions. Also - running this only changes the courses i expect so i think its narrow enough?

2022-01-14 14:04 UTC, JamesyJi approved these changes

2022-01-14 14:10 UTC, JamesyJi requested changes
Remove the backend. on imports because we run everything from the backend/ folder (I mean I guess you could shift everything to run from the root but at this point, the venvs, imports in other files, docker, everything is written with this assumption so it's best to keep it imo.

2022-01-15 07:57 UTC, JamesyJi approved these changes

2022-01-15 07:57 UTC, merged