Leo/tp/cf 188 make unplanned column fixed
csesoc/Circles pull request #453
Opened 2022-05-09 16:39 UTC by leonardo-fan

- unplanned column now always visible (absolute) despite scrolling the main container
- overflow on y axis
- support for different screen sizes
- support for summer term and normal term sizes
![unplanned always visible](https://user-images.githubusercontent.com/90736577/167456741-4c1b2c70-ef17-4bde-98e6-e05995063d27.gif)

2022-05-09 22:50 UTC, gtangelo requested changes
Didn't realise it would need js calc for make it fixed haha. Yeet everything looks good to me!

There's one bug I found:
- There's a bug where if there are not any courses in the unplanned column, the width shrinks:
![image](https://user-images.githubusercontent.com/65492346/167511012-7a56d27b-964e-4032-ae53-7a40896ed412.png)

2022-05-09 22:50 UTC, gtangelo commented on frontend/src/pages/TermPlanner/TermPlanner.jsx
> +              <div className="gridItem" />
Maybe add a comment saying that this empty div is for adding the spacing for the fix unplanned column?

2022-05-10 01:24 UTC, leonardo-fan commented
Nice, sure will fix those things now!

2022-05-14 05:12 UTC, Peedee2002 approved these changes
lgtm

2022-06-10 05:23 UTC, leonardo-fan commented
refer to new description and demo :)

2022-06-10 05:39 UTC, leonardo-fan commented
ahh, just found a bit of a weird thing because of the absolute positioning when the screen width gets too small, not too sure how to fix it 🆘 

https://user-images.githubusercontent.com/90736577/172997727-652c26a7-544d-4b9c-8d5a-8e6aee704a3a.mov

2022-06-10 05:53 UTC, gtangelo approved these changes
Very nice! lgtm! This looks simplier compared to the ref approach but the css calc could be confusing (not a bad thing, I don't disagree with the approach but I guess it's a con of using css instead haha). Still pretty nice to see the unplanned column tho!!

I'm happy for this to be merged now 🥳. But some minor things/bugs I noticed (not a deal breaker and more of edge cases).

@leonardo-fan if you just want to merged this in and not want to fix the bugs below, pls create tickets just to take note of it in the backlog and we can address it in a later time 😅.

- Is it possible to change the background of the overflow scroll to a white color rather than a grey like color?
![image](https://user-images.githubusercontent.com/65492346/172999492-90eb7d46-dffc-4687-ae42-b45a53529c07.png)
- When summer term is enabled, unplanned is not padded for higher res screens ripp. I'm happy for this to be merged without fixing it. If you don't want to fix it, create a bug ticket for it on Jira. If you do want to fix it, fix it haha. Up to u :)
![image](https://user-images.githubusercontent.com/65492346/172996855-938a879a-80e2-4dd9-b0ed-66603bd9106d.png)
- When dragging the course back to the unplanned column, the x-scroll appears for a second until it has been placed. Not a huge breaker. Likewise, create a bug ticket on Jira for someone else to fix it later on. But I believe it should just be a css change i.e. add overflow-x to none?
![image](https://user-images.githubusercontent.com/65492346/172997280-7def88b4-5a56-435d-876d-c0deeff21e60.png)

Nice work!! 😎 

EDIT: Just saw ur comment on the smaller screens, don't think we need to worry about smaller screens lol. Just create a bug ticket on jira in the backlog to make a mental note of it.

2022-06-10 05:53 UTC, gtangelo commented on frontend/src/pages/TermPlanner/UnplannedColumn/index.less
> +    100vh - (
oof alot of calcs haha. Not visually readable but I think this is the simpliest approach to do the unplanned column. Maybe could add a brief comment explaining why it's using calc?

2022-06-10 05:53 UTC, gtangelo commented on frontend/src/pages/TermPlanner/UnplannedColumn/index.less
> +  font-weight: bold;
UI change, change it to `500` or `600` rather than `bold`? Seems a bit bold imo

2022-06-10 05:53 UTC, gtangelo commented on frontend/src/pages/TermPlanner/UnplannedColumn/index.less
> +  border: 2px solid #9254de;
I like the border-color, but imo the px should be between 1.5px to 2px? 2px feels a bit to thick for the border. But totally up to you on which looks best. Don't mind either way :D

2022-06-10 06:53 UTC, merged