added the script that summarises changes.
csesoc/Circles pull request #471
Opened 2022-05-15 11:27 UTC by Peedee2002

example output (2021):
`
the following courses have been removed:
{'PHYS1116', 'ECON3000', 'DPHU1001', 'ZEIT3752', 'LAWS2277', 'DPDE1009', 'DPDE1007', 'DPDE1003', 'PSYC3199', 'ZEIT4150', 'DPHU1006', 'ECON3127', 'MDCN8888', 'ZHSS3238', 'BABS3199', 'PSYC3299', 'ARTS3491', 'MDCN8000', 'MGMT3004', 'ZEIT4152', 'COMP6991', 'DPHU1004', 'CHEM3199', 'ZPEM1503', 'ACTL3143', 'DESN3210', 'DESN1010', 'MANF9550', 'ZHSS3750', 'ARTS3490', 'INFS3822', 'ZEIT3753', 'ZEIT4153', 'ARTS2465', 'MATH3051', 'ZPEM2405', 'SENG3994', 'DPHU1002', 'DPDE1011', 'MATH3371', 'COMM6700', 'MERE2001', 'FOOD3060', 'TELE9757', 'ZEIT3751', 'DPHU1005', 'ZEIT4750', 'ZBUS3310', 'CHEM3299', 'INFS1701', 'INFS2701', 'AVIA3199', 'ARTS2488', 'DART2213', 'COMM3091', 'FADA6700', 'BABS3299', 'COMP9727', 'BEES3199', 'LAWS3250', 'MERE2002', 'INFS3701', 'DPDE1001', 'ZPEM1504', 'FINS2615', 'DESN3000', 'SENG3993', 'ZEIT4151', 'CDEV2000', 'GMAT4060', 'PATH3210', 'DPDE1006', 'DPDE1008', 'CHEM2701', 'MTRN4231', 'INFS3703', 'MATS3299', 'DPHU1007', 'LAWS1055', 'DPDE1005', 'AVIA3299', 'DPHU1003', 'CDEV3012', 'MATS3199', 'DPDE1004', 'DESN1000', 'MFAC4999', 'MATH3191', 'PHYS3199', 'DPDE1010', 'DESN3200', 'ZBUS3378', 'ARTS3577', 'ZBUS2333', 'DPHU1008', 'ZEIT4752', 'BEES3299', 'CDEV3101', 'ARTS2068', 'ELEC3146', 'ZEIT4751', 'PHYS3299', 'ZEIT3750', 'INFS2609', 'INFS3700', 'DESN1900', 'ARTS2042', 'GMAT4061', 'SOMS3199', 'DPDE1002', 'MDCN8889', 'DART2151', 'INFS2702', 'MFAC4001'}
======================================
the following courses have been added:
{'YMED3001', 'BEES4515', 'COMM1001', 'SOMA3414', 'LAND2402', 'ELEC2146', 'BABS3091', 'CVEN4401', 'TABL3025', 'SOMA3408', 'COMP6449', 'ADAD3400', 'SART2416', 'ADAD2400', 'SART3415', 'SART1502', 'CEIC3003', 'TABL1011', 'DART2330', 'YMED1002', 'GENE1015', 'GEOS3611', 'PTRL2030', 'SART1501', 'SART3400', 'SOMA3416', 'INFS2848', 'ADAD4010', 'CHEM2996', 'SOMA2411', 'ECON2104', 'PHCM3006', 'ARTS3279', 'TABL3031', 'MINE4510', 'ZHSS3228', 'CVEN4501', 'INTA2301', 'SART2412', 'CVEN2702', 'DART3391', 'TABL3007', 'SART3404', 'SART2408', 'SART1312', 'BIOT3081', 'ENGG1000', 'INDC2003', 'LAWS3789', 'ADAD1001', 'PTRL1010', 'LAND2302', 'GENC2100', 'BIOM5930', 'BIOM5001', 'SOMA2408', 'INDC3001', 'MATS4501', 'GMAT4900', 'COMM4002', 'SDES2464', 'SOMA3415', 'SART2407', 'HUMS1004', 'SART2415', 'ADAD4011', 'AERO4120', 'AVIA4001', 'SART3413', 'SOMA3412', 'MGMT3708', 'GMAT4009', 'SAHT2680', 'MFAC4508', 'TABL1710', 'SAHT2480', 'SART3403', 'CEIC3002', 'SART2413', 'TABL3028', 'GENM0510', 'SART3412', 'SART3411', 'SDES2116', 'ADAD1100', 'BABS7010', 'ZEIT4222', 'SART1313', 'YMED3003', 'ZPEM3524', 'SOMA2414', 'CVEN4002', 'YMED1006', 'ZPEM1402', 'OPTM4211', 'FINS3634', 'SART2829', 'SOMS4001', 'SOMA2415', 'SOMA1001', 'MICR4013', 'SDES3403', 'YMED3002', 'CVEN2301', 'ENGG4820', 'CVEN4702', 'ZEIT3302', 'ELEC0390', 'GENM0519', 'SART3408', 'ARTS3817', 'ECON4311', 'HUMS2004', 'SART2842', 'SART2841', 'SOMA2815', 'SAHT3131', 'COMP9844', 'OPTM5231', 'MGMT1001', 'SOMA2818', 'ARTS3068', 'SERV9999', 'BEES4514', 'SOMS4002', 'ARTS3372', 'MECH9223', 'MGMT1101', 'PLAN4031', 'PTRL4041', 'ADAD3402', 'INTA2202', 'ECON2127', 'INDC3002', 'COMP1000', 'SDES2201', 'ARTS2905', 'CVEN1300', 'SOMA2863', 'SDES3400', 'PHCM4013', 'ZINT1006', 'TABL1006', 'MFAC3507', 'SOMA2816', 'SART3402', 'LAND2401', 'BABS4524', 'SOMA2605', 'SAED4491', 'CDEV1112', 'LAWS3019', 'ARTS2484', 'CHEM4004', 'ECON2322', 'CVEN4403', 'AVIA3014', 'MARK4213', 'SOMA2413', 'BIOT4073', 'ZPEM2209', 'SART2404', 'SDES1111', 'ADAD3114', 'EDST6724', 'ZBUS2304', 'SDES2407', 'DART1303', 'GENM0520', 'SART3410', 'MATS4010', 'LAWS3147', 'PTRL3023', 'EDST6708', 'MINE4610', 'SDES3405', 'SART3417', 'OPTM2291', 'CVEN4310', 'OPTM4271', 'TABL3055', 'COMP9433', 'CHEM4003', 'BENV6800', 'EDST6720', 'CVEN4305', 'CVEN3731', 'ENVS2030', 'GEOS2641', 'VISN3211', 'FOOD9410', 'CVEN3201', 'OPTM4231', 'SART2400', 'SOMA3801', 'SDES3410', 'SOCW3001', 'SART3801', 'SOMS3212', 'SART2410', 'OPTM5171', 'ZEIT4705', 'SART2417', 'SART2501', 'SART1311', 'PTRL2018', 'EDST6743', 'MFAC2505', 'SAHT4211', 'INTA2201', 'CHEM4005', 'ADAD2402', 'MINE3000', 'PLAN0081', 'CVEN2201', 'COMP6324', 'ZHSS2204', 'SART3401', 'PTRL3002', 'AVIA2014', 'PHTN3117', 'FOOD5400', 'SOMA3411', 'BEES0010', 'INTA2101', 'SDES1211', 'TABL3022', 'OPTM2190', 'NANO3002', 'MANF4020', 'CHEM4524', 'EDST6750', 'GENS5003', 'EDST6754', 'MFAC2506', 'OPTM4151', 'PLAN4132', 'FOOD3901', 'SDES2406', 'YMED1004', 'FOOD9430', 'SART3414', 'MINE2010', 'TABL2053', 'LAWS3141', 'COMP1400', 'ACCT1501', 'LAWS3142', 'FOOD1360', 'TABL4721', 'FINS4775', 'AVIA2950', 'CHEN6710', 'FINS3649', 'SART1641', 'TABL2732', 'MFAC3510', 'SART2836', 'INTA2102', 'SOMA2412', 'SART3409', 'ZEIT4016', 'ZEIT4505', 'ADAD0600', 'MARK1014', 'CVEN4101', 'SART3416', 'ARTS3486', 'MATS4500', 'ZHSS3422', 'SART2405', 'CVEN4003', 'PTRL1001', 'CHEM4006', 'SART2859', 'SART2401', 'CEIC2004', 'SART3800', 'INFS4893', 'MUSC2111', 'TABL2059', 'MANF3610', 'ADAD1002', 'PHTN4123', 'CVEN2302', 'TELE4123', 'SART2411', 'ELEC1112', 'PTRL2114', 'TABL1003', 'CVEN2501', 'TABL3033', 'BABS4053', 'SDES2403', 'AVIA2013', 'TABL1005', 'ARTS3055', 'HUMS2000', 'TABL2057', 'ACCT1511', 'TABL2015', 'SDES2400', 'GENM0708', 'MINE3800', 'NANO1001', 'MINE4320', 'GMAT2130', 'CVEN4502', 'TABL2060', 'SDES3402', 'GENM0518', 'TABL1010', 'CVEN3301', 'SDES3401', 'GENS4008', 'BEES2051', 'SDES3172', 'DART3390', 'GMAT4450', 'SDES2184', 'ARTS2303', 'DART1390', 'TELE3117', 'SART3406', 'SOMA2481', 'SOMA2410', 'ARTS3816', 'SOMA2409', 'SOMA3413', 'MINE4820', 'VISN2231', 'MARK1012', 'ZEIT4015', 'OPTM4291', 'MFAC4501', 'SOMA3410', 'FINS2613', 'OPTM4131', 'GMAT9300', 'FOOD9420', 'GENC5031', 'OPTM4251', 'OPTM3131', 'GMAT3600', 'ZPEM3203', 'BEES4518', 'SART1314', 'SDES2413', 'OPTM4110', 'SART2403', 'DDES1290', 'SAHT4213', 'EDST6713', 'LAND2301', 'TABL2058', 'MINE4440', 'TELE4121', 'OPTM3231', 'EDST6738', 'PTRL4040', 'BEES4523', 'MECH9660', 'LAWS3356', 'OPTM5271', 'DDES2180', 'CVEN4307', 'MDCN8002', 'SAHT3690', 'MDIA2001'}
======================================
the following courses have had their prerequisites changed:
ECON4106
from: Admission to Economics Honours (program 4502 or stream ECONFH4501) or Actuarial Honours (program 4520)
to: Admission to Economics Honours (program 4502 or stream ECONFH4501)
AERO4620
from: Prerequisite: AERO3660 and (MMAN3200 or ELEC3114)
to: Prerequisite: AERO3660 and MMAN3200
COMM1900
from: Pre-req: (ECON1101 and ECON1102) or (DPBS1101 and DPBS1102)
to: Enrolment is only permitted for students in program Actl/Comm (3155) or Comm/Econ (3521).<br/>Pre-req: (ECON1101 and ECON1102) or (DPBS1101 and DPBS1102)
CHEM1031
from: 
to: Prerequisite: Must be enrolled in a program with the option of a CHEM major
ARTS4822
from: Prerequisite: Enrolment in the Spanish Studies honours program
to: Prerequisite: Enrolment in the Spanish and Latin American Studies honours program
MGMT3701
from: Prerequisite: MGMT1001 or COMM1100 or COMM1170 or COMM1120 or MGMT2718
to: Prerequisite: MGMT1001or COMM1170
CEIC3007
from: Co-requisite: CEIC3006Pre-requisite: CEIC2007 and CEIC3001 and CEIC3005 and MATH2089
to: 
MANF4100
from: Prerequisite: (DESN1000 OR DPST1071) AND (MMAN1130 OR MMAN2130)
to: Prerequisite: (ENGG1000 OR DPST1071) AND (MMAN1130 OR MMAN2130)
ARTS3755
from: Prerequisite: 48 UOC overall, including 6 UOC at level 1 and 6 UOC at level 2 in one of the following specialisations, Development Studies, Geographical Studies or Global Development. Or 48 UOC overall and enrolment in an International Studies program
to: Prerequisite: 48 UOC overall, including 6 UOC at level 1 and 6 UOC at level 2 in one of the following streams, Development Studies, Global Development
BLDG4019
from: Program Prerequisite: 4522
to: Program Prerequisite:4522 or Program 3332 with WAM of 65 or over
INTA3000
from: Prerequisites: INTA1000, INTA2000, INTA2101, INTA2102
to: Prerequisites: INTA1000, INTA2000, INTA2101, INTA2102, BENV0001
COMM2501
from: Prerequisite: (ECON1203 or COMM1190 or MATH1151 or MATH1141 or MATH1131) and (COMM1822 or ACTL1101 or COMP3311) [...]

2022-05-15 13:42 UTC, imagine-hussain requested changes
I like the method of taking the diff between the individual elements; I think it's quite clean.

Would just like to see a bit more visual separation on the output to make it easier to read.

Otherwise looks good to me.

Also, I hate to be that person but, the following pylint output should probably be addressed before merging:
> ************* Module runcomparison
backend/runcomparison.py:41:0: C0303: Trailing whitespace (trailing-whitespace)
backend/runcomparison.py:70:0: C0304: Final newline missing (missing-final-newline)
backend/runcomparison.py:39:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
backend/runcomparison.py:42:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
backend/runcomparison.py:64:21: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)

2022-05-15 13:42 UTC, imagine-hussain commented on backend/runcomparison.py
> +    print(courses_in_manual)
could we get a newline at end of file

2022-05-16 08:25 UTC, joooooooooooooooooooooooooooooooooooosh approved these changes

2022-05-16 11:25 UTC, Peedee2002 commented
@imagine-hussain i agree on trying to make the output easier to parse, but i am not too sure what i can change. Any suggestions? I already expanded the seperators, but are there any other ideas?

2022-05-16 11:39 UTC, imagine-hussain commented
> @imagine-hussain i agree on trying to make the output easier to parse, but i am not too sure what i can change. Any suggestions? I already expanded the seperators, but are there any other ideas?

@Peedee2002 

I'm not sure how much can be done, other than just whitespace between components. Perhaps we could play with colouring / syntax highlighting but i'm not sure if you wanna go down that route.

The other thing I could think of, is having the output be indented somewhat like yaml syntax. This way it can be piped to a temp file and opened in a text editor. This gives us both highlightingh and also, access to editor features like collapsing portions that we don't care about.

So we would have something like:
```yml
course1:
    - from: lorem ipsum
    - to:   lorem ipsum but longer
course2:
    - from: aBDC
    - to:    DEFG
```

I guess if we are to go down that route, we can just have it output to a file by default? Or maybe have that as a setting in the arguments; just make sure to put that file in the gitignore.

2022-05-16 12:28 UTC, Peedee2002 commented
@imagine-hussain I like the idea of indentation and yaml-like format. I wont make a new file (we can just run `python runprocessors -t 2021 > file` if we really want to output to a file) but ill make it yaml-like so we can get syntax highlighting. Here is an example output file:
[hi.txt](https://github.com/csesoc/Circles/files/8700007/hi.txt)
(change the extension to yaml, for some reason github is stupid when it comes to file upload)

2022-05-16 12:52 UTC, banaboi approved these changes

2022-05-17 02:41 UTC, imagine-hussain approved these changes
lgtm

2022-05-17 02:41 UTC, merged