Luke/circles 322
csesoc/Circles pull request #483
Opened 2022-05-21 06:40 UTC by banaboi

Created a python script which will run the whole app without much use of docker (the database is started using it but that's it). The script will also log all console output from the frontend and backend into a .log file called 'debug'. The script is currently running at the top directory but that can change if we want.

2022-05-22 12:53 UTC, joooooooooooooooooooooooooooooooooooosh approved these changes

2022-05-23 05:03 UTC, imagine-hussain requested changes
Can we get the `debug.log` (or really all `.log` files) added to the git ignore?
Otherwise, the script LGTM.

2022-05-23 11:12 UTC, hdphuong approved these changes

2022-05-23 13:20 UTC, Peedee2002 approved these changes

2022-05-23 14:07 UTC, imagine-hussain approved these changes
lgtm

2022-05-23 14:07 UTC, Peedee2002 commented
have a look at the pylint issues tho

2022-05-26 06:36 UTC, merged