Uzaif/cf 202
csesoc/Circles pull request #521
Opened 2022-06-09 14:07 UTC by Uzaif-Sheikh

Added total UOC for the terms and each year.

2022-06-10 05:14 UTC, gtangelo requested changes
lgtm! Just fixed the merge conflicts and comments made.

One minor UI improvement, could you center the total UOC? Currently, it is looking a bit off-centered

2022-06-10 05:14 UTC, gtangelo commented on frontend/src/pages/TermPlanner/TermBox/TermBox.jsx
> +  // eslint-disable-next-line
remove this eslint comment if we are not disabling next line

2022-06-10 05:14 UTC, gtangelo commented on frontend/src/pages/TermPlanner/TermBox/TermBox.jsx
> -  name, courses, termsOffered, isDragging, showMarks,
Why are we removing `showMarks` here from the param? Think this may break the marks feature...

2022-06-10 05:14 UTC, gtangelo commented on frontend/src/pages/TermPlanner/TermBox/TermBox.jsx
> +  useEffect(() => {
could be simplified to

```
useEffect(() => {
    let uoc = 0;
    Object.keys(courses).forEach((c) => {
      if (coursesList.includes(c)) uoc += courses[i].UOC;
    });
    setTotalUOC(count);
}, [coursesList])
```

2022-06-12 05:58 UTC, Uzaif-Sheikh commented on frontend/src/pages/TermPlanner/TermBox/TermBox.jsx
> -  name, courses, termsOffered, isDragging, showMarks,
ah, I think while resolving the conflict I clicked on accept current changes, I will fix it.

2022-06-12 08:34 UTC, gtangelo approved these changes
lgtm!

2022-06-12 09:06 UTC, merged