feat(degree-wizard): expose major and minor notes
csesoc/Circles pull request #545
Opened 2022-06-20 10:38 UTC by ollibowers

Displays the degree notes for major and minors now. 
Changes made:
- added ternaries to show the notes when present (by putting them in a menu itemgroup)

![image](https://user-images.githubusercontent.com/80164276/174584162-c6eb2fca-d45f-4647-9824-69dd22f933dd.png)
![image](https://user-images.githubusercontent.com/80164276/174584224-ef31d5e7-ba33-49d9-a06e-1c104d72fe67.png)

Note: was not able to test for empty notes, but should account for them.

2022-06-20 13:07 UTC, gtangelo approved these changes
Lgtm!

2022-06-20 13:07 UTC, gtangelo commented on frontend/src/pages/DegreeWizard/steps/MinorStep.jsx
> +            {(options[sub].notes !== "")
Nitpick: Would 'options[sub].notes' rather than 'options[sub].notes != ""' still evaluate the same (think so)? Maybe do thAt instead for style 😅

2022-06-20 13:07 UTC, gtangelo commented on frontend/src/pages/DegreeWizard/steps/SpecialisationStep.jsx
> +            {(options[sub].notes !== "")
Same notes as above

2022-06-22 13:41 UTC, gtangelo requested changes
@ollibowers Some changes were made for the degree wizard recently which means that we dont have a `MinorStep.jsx`. Please fix this when you can :D

2022-06-23 09:10 UTC, ollibowers reviewed
Changes have been resolved!

2022-06-23 09:34 UTC, gtangelo approved these changes
lgtm! again 👀

2022-06-24 05:13 UTC, merged