feat/CIRCLE-331: Migrating user data to backend
csesoc/Circles pull request #610
Opened 2022-07-15 07:51 UTC by imagine-hussain

2022-08-18 13:07 UTC, zaxutic approved these changes
didn't read but lgtm

2022-08-18 13:15 UTC, Peedee2002 commented
> didn't read but lgtm

![image](https://user-images.githubusercontent.com/64952797/185403911-717ff52e-bbd3-4e96-9607-2d4fc7a07d11.png)
mmhmm shippable code
yummy yummy raw html

2022-08-19 15:46 UTC, imagine-hussain commented
> didn't read but lgtm

real

2022-09-28 05:01 UTC, lhjt requested changes

2022-09-28 05:01 UTC, lhjt commented on .github/workflows/ci_BE.yml
> +    branches: [dev, main, CIRCLES-331/user-data-to-backend]
This (and other occurrences) need to be removed
```suggestion
    branches: [dev, main]
```

2022-09-28 05:01 UTC, lhjt commented on backend/server/config.py
> +CLIENT_ID = "1017197944285-i4ov50aak72667j31tuieffd8o2vd5md.apps.googleusercontent.com"
This shouldn't be hardcoded and extracted to an environment variable

2022-09-28 05:01 UTC, lhjt commented on backend/server/database.py
> +    # TODO: DELETE NEXT LINE IN PROD
(I assume this should be removed?)

2022-09-28 05:01 UTC, lhjt commented on backend/server/routers/auth.py
> +    return token
Uh (?)

2022-09-28 05:01 UTC, lhjt commented on frontend/src/pages/Auth/Auth.tsx
> +/* eslint-disable */
Why is this included?

2022-09-28 05:01 UTC, lhjt commented on frontend/src/pages/Auth/Auth.tsx
> +      client_id: "1017197944285-i4ov50aak72667j31tuieffd8o2vd5md.apps.googleusercontent.com",
Should be injected at build time via environment variable

2022-09-28 05:02 UTC, lhjt commented
Oh rip this was marked as ready to review as I was reviewing it my bad

2022-09-28 05:05 UTC, Peedee2002 commented
sorry @lhjt i was trying to update the branch from my phone

2022-10-04 00:09 UTC, Peedee2002 commented on backend/server/database.py
> +    usersDB.create_collection('users',
example validation

2022-10-04 00:11 UTC, Peedee2002 commented on backend/server/routers/user.py
> +        'degree': localStorage.degree,
example insert

2022-10-04 00:12 UTC, Peedee2002 commented on backend/server/routers/model.py
> +class Storage(TypedDict):
thing i am typechecking (?)

2023-02-18 06:15 UTC, imagine-hussain commented on backend/server/routers/auth.py
> +    return token
TODO:

2023-02-18 06:28 UTC, imagine-hussain commented on backend/server/config.py
> +CLIENT_ID = "1017197944285-i4ov50aak72667j31tuieffd8o2vd5md.apps.googleusercontent.com"
agreed; will be done *eventually*

2023-03-22 02:55 UTC, closed without merging