Comm manual fixes
csesoc/Circles pull request #93
Opened 2021-09-27 04:16 UTC by VincentXiao-jpg

Added the DS_Store ignore back to frontend

2021-10-05 09:58 UTC, JamesyJi requested changes
Business school courses r just doomed honestly gg

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +    return ""
Can you return this as a warning? Refer to your condition below as an example

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +    }
Can you add warning about the Term 2 and Term 3 thing?

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +# def COMM_1120(conditions):
Best to comment the return out as well (idk how the behaviour is working here)

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +# def COMM_1140(conditions):
Likewise here

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +# def COMM_1170(conditions):
Likewise here and below, remember to comment out the entire function or else there's a bunch of floating returns (which probably breaks the code when we run it)

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +    }
Change ZBUS to ZBUS#

Add in warning field about good standing and how co-op students are excluded

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +    return "(COMM6000 || COMM1999) && 48UOC"
Add in a warning field for good standing

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +    return "(COMM6000 || COMM1999) && 65WAM && 72UOC"
Should be 48UOC not 72

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +        "warning": "Students are expected to be in their final year of a Bachelor of Commerce single or dual degree with at least 108 UOC completed."
Shorten warning to "Students are expected to be in their final year of a Bachelor of Commerce single or dual degree"

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +        "warning": "This course is by application only.Please contact the Co-op office for more information. Students who have completed DIPP1510 or COMM2222 or are in Business Co-Op programs are exc
Take out the DIPP1510 and COMM2222 and add to exclusions

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +    COURSES["COMM3202"]["exclusions"]["COMM222"] = 1
Missing a 2 here

2021-10-05 09:58 UTC, JamesyJi commented on backend/data/processors/manualFixes/COMMFixes.py
> +        "warning": "Studetns must be in their final year"
Misspelt students in warning

Change 72UOC to `72UOC in ZBUS`

2021-12-21 11:34 UTC, merged

2022-04-20 15:34 UTC, lhjt commented
Closing for renovate.