feat: Replace addToUnplanned with API
csesoc/Circles pull request #989
Opened 2023-03-07 01:56 UTC by LukePrior

2023-03-22 05:26 UTC, leonardo-fan requested changes
noice, just a small change

2023-03-22 05:26 UTC, leonardo-fan commented on backend/server/routers/planner.py
> +    if data.courseCode in user['courses'].keys() or data.courseCode in user['planner']['unplanned']:
check `user['planner']['courses']` instead as `user['courses']` maintains all the courses available

2023-03-22 05:29 UTC, imagine-hussain approved these changes

2023-03-22 05:51 UTC, leonardo-fan approved these changes, later dismissed
lgtm

2023-03-23 11:11 UTC, leonardo-fan approved these changes

2023-03-25 06:33 UTC, merged